/**
 * Generated by scripts/prebuild-env.mjs from NG_APP_API_URL before production builds.
 * Do not edit by hand — set NG_APP_API_URL (e.g. in Vercel Environment Variables).
 */
export const NG_APP_BUILD_API_URL = "https://api.example.com";
