import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outFile = path.join(root, 'src/environments/ng-app-api-url.generated.ts');
const url = process.env.NG_APP_API_URL ?? '';

const content =
  `/**\n` +
  ` * Generated by scripts/prebuild-env.mjs from NG_APP_API_URL before production builds.\n` +
  ` * Do not edit by hand — set NG_APP_API_URL (e.g. in Vercel Environment Variables).\n` +
  ` */\n` +
  `export const NG_APP_BUILD_API_URL = ${JSON.stringify(url)};\n`;

fs.writeFileSync(outFile, content, 'utf8');
